[package]
name = "picon"
version = "0.0.0"
edition = "2024"
authors = ["Giuliano Bellini <gyulyvgc99@gmail.com>"]
description = "Get process icons on Windows, macOS, and Linux"
readme = "README.md"
repository = "https://github.com/GyulyVGC/picon"
license = "MIT"
keywords = ["process", "path", "icon"]
categories = ["filesystem", "os"]
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md", "examples/**/*"]

[target.'cfg(target_os = "macos")'.dependencies]
objc2-foundation = { version = "0.3.1", default-features = false, features = ["NSString"] }
objc2-app-kit = { version = "0.3.1", default-features = false, features = ["NSWorkspace", "NSImage"] }

[target.'cfg(target_os = "linux")'.dependencies]
shellexpand = "3.1.1"
